### PR TITLE
New aur packages

### PR DESCRIPTION
**Pull request by kprkpr**
Hi!
I'm Kevin, from JKANetwork. We maintain a repo, but when I discovered that project and started to see telegram chat, we talked to the rest and say that if we can, we will do a Spain mirror of chaotic-aur and migrate from our repo to yours. We had much packages same in the two, and if you want to add that packages in your repo, we will thank a lot!

### CODE REVIEW

**Comment by PedroHLC** [comment]
:smile: hey, thanks for the help! But no need for the pull-request tough, I'm studying how I'll remake the infra (again), and by now, I'll just add those packages by hand.

I'll close this PR as soon as I finish them...

**Comment by PedroHLC** [comment]
About the mirroring, we have a script for rsync ready. But I  currently prefer doing the mirroring through syncthing. This way, the mirrors help each other.

You can contact me through [telegram](t.me/pedrohlc), and all let you know the details. As well as add it to the mirror list and publish it when it's ready.

**Comment by PedroHLC** [comment]
A few of these packages didn't built, you can see their logs here:
https://lonewolf.pedrohlc.com/chaotic-aur/makepkglogs/_lab/jkanetwork/

I recommend first suggesting fixes to the AUR's pacakge maintainers.
If that's not possible then let me know and I'll apply some server-side automated adjusts.

**Comment by kprkpr** [comment]
Hi
I will contact you in Telegram (Syncthing is a great app!). We are updating our infra this days too
I'm seeing errors and fixing it. About openlitespeed, I'm the maintainer, and fixed it, but I can't build newer than 1.5.X with sources, it changed the way to build to one tightened to Ubuntu and so, then I created a openlitespeed-bin one that seems to work. I prefer source, but until that can be adapted..
You can delete localepurge suggestion, all are changing to a pacman config instead installing localepurge (Is Debian thing)
Pimagizer I wrote to maintainer the fix
I'm seeing freefilesync

**Comment by kprkpr** [comment]
About freefilesync error, in my computer doesn't say anything about dlagent in a clean "base-devel" chroot with deps installed.. Maybe some security in chroot?

**Comment by PedroHLC** [comment]
> Maybe some security in chroot?
 It was just a problem with the relative path. I've fixed it with a `cd`. Interesting (for me) that I never had any problem with it in 2 years.

**Pull request closed without merging**
