### PR TITLE
Replace issue template with forms

### PR DESCRIPTION
**Pull request by ObserverOfTime**
This pull request replaces the legacy issue template with the new [forms].

[forms]: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

### CODE REVIEW

**Comment by dr460nf1r3** [comment]
Very interesting, thanks for enhancing the template! :)

**Comment by dr460nf1r3** [comment]
Its marvelous!

**Comment by Technetium1** [comment]
Great job @ObserverOfTime, I was hoping someone would do this!

**Comment by PedroHLC** [comment]
Wow, this is awesome!

**Pull request merged**
