### PR TITLE
add spleeter-git & update .gitignore

### PR DESCRIPTION
**Pull request by xiota**
See #2519

```
python-musdb # (dep spleeter-git python-museval)
python-museval # (dep spleeter-git)
python-norbert # (dep spleeter-git)
python-soundfile # (dep python-musdb python-museval python-stempeg)
python-stempeg # (dep python-musdb python-museval)
spleeter-git
```

Also, changing `.gitignore` to whitelist instead of blacklist.

### CODE REVIEW

**Review by dr460nf1r3 — APPROVED** [review]
Nice!

**Review by Technetium1 — APPROVED** [review]
If there's no more deps to be added [(like these commented ones)](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=spleeter-git#n25) then it looks good to merge!

**Comment by xiota** [comment]
It looks like the program has problems downloading the training data, so I'm creating a separate package with training data.  It's ~70MB.  Would it be okay to add?

**Comment by Technetium1** [comment]
@xiota yes that would be appropriate

**Pull request merged**
